base_link: base_link
models:
 - name: group1
   type: chain
   frame: link_6
 - name: camera
   type: camera3d
   frame: camera_optical_frame
   topic: /camera/depth_registered/points
free_params:
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
free_frames:
  - name: checkerboard_1
    x: true
    y: false
    z: true
    roll: false
    pitch: true
    yaw: false
  - name: light_source_1
    x: true
    y: false
    z: true
    roll: false
    pitch: true
    yaw: false
error_blocks:
 - name: arm_to_camera
   type: chain3d_to_chain3d
   model_a: group1
   model_b: camera
 - name: restrict_camera
   type: outrageous
   param: camera_optical_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1