chains:
  - name: group1
    topic: /joint_trajectory_action
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    planning_group: group1
duration: 10.0
features:
  checkerboard_finder_1_mt:
    type: robot_calibration/CheckerboardFinder
    topic: /camera_1/depth_registered/points
    camera_sensor_name: mounted_camera
    chain_sensor_name: group1
    checkerboard_frame_name: checkerboard_1
    points_x: 6
    points_y: 4
    size: 0.038
  checkerboard_finder_2_mt:
    type: robot_calibration/CheckerboardFinder
    topic: /camera_1/depth_registered/points
    camera_sensor_name: mounted_camera
    chain_sensor_name: group1
    checkerboard_frame_name: checkerboard_2
    points_x: 4
    points_y: 3
    size: 0.048
  checkerboard_finder_3_mt:
    type: robot_calibration/CheckerboardFinder
    topic: /camera_1/depth_registered/points
    camera_sensor_name: mounted_camera
    chain_sensor_name: group1
    checkerboard_frame_name: checkerboard_3
    points_x: 5
    points_y: 3
    size: 0.042
  checkerboard_finder_1_ex:
    type: robot_calibration/CheckerboardFinder
    topic: /camera_2/depth_registered/points
    camera_sensor_name: external_camera
    chain_sensor_name: group1
    checkerboard_frame_name: checkerboard_1
    points_x: 6
    points_y: 4
    size: 0.038
  checkerboard_finder_2_ex:
    type: robot_calibration/CheckerboardFinder
    topic: /camera_2/depth_registered/points
    camera_sensor_name: external_camera
    chain_sensor_name: group1
    checkerboard_frame_name: checkerboard_2
    points_x: 4
    points_y: 3
    size: 0.048
  blinking_light_source_finder_ex:
    type: robot_calibration/BlinkingLightSourceFinder
    topic: /camera_2/depth_registered/points
    camera_sensor_name: external_camera
    chain_sensor_name: group1
    light_source_frame_name: light_source_1