chains:
  - name: group1
    topic: /joint_trajectory_action
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    planning_group: group1
duration: 10.0
features:
  checkerboard_finder:
    type: robot_calibration/CheckerboardFinder
    topic: /camera/depth_registered/points
    camera_info_topic: /camera/depth/camera_info
    camera_sensor_name: camera
    chain_sensor_name: group1
    checkerboard_frame_name: checkerboard
    points_x: 4
    points_y: 3
    size: 0.048