chains:
  - name: group1
    topic: /joint_trajectory_action
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    planning_group: group1
duration: 10.0
features:
  checkerboard_finder:
    type: robot_calibration/CheckerboardFinder
    topic: /camera/depth_registered/points
    camera_sensor_name: camera
    chain_sensor_name: group1
    points_x: 7
    points_y: 5
    size: 0.030
  checkerboard_finder_2:
    type: robot_calibration/CheckerboardFinder
    topic: /camera/depth_registered/points
    camera_sensor_name: camera
    chain_sensor_name: group1
    points_x: 6
    points_y: 4
    size: 0.030
  checkerboard_finder_3:
    type: robot_calibration/CheckerboardFinder
    topic: /camera/depth_registered/points
    camera_sensor_name: camera
    chain_sensor_name: group1
    points_x: 5
    points_y: 3
    size: 0.030