base_link: base_link
models:
 - name: group1
   type: chain
   frame: link_6
 - name: mounted_camera
   type: camera3d
   frame: mounted_camera_optical_frame
   topic: /mounted_camera/depth_registered/points
 - name: external_camera
   type: camera3d
   frame: external_camera_optical_frame
   topic: /external_camera/depth_registered/points
free_params:
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
  - camera_fx
  - camera_fy
  - camera_cx
  - camera_cy
  - camera_z_offset
  - camera_z_scaling
free_frames:
  - name: checkerboard_1
    x: true
    y: false
    z: true
    roll: false
    pitch: true
    yaw: false
  - name: checkerboard_2
    x: true
    y: false
    z: true
    roll: false
    pitch: true
    yaw: false
  - name: checkerboard_3
    x: true
    y: false
    z: true
    roll: false
    pitch: true
    yaw: false
  - name: light_source_1
    x: true
    y: false
    z: true
    roll: false
    pitch: true
    yaw: false
  - name: external_camera_optical_joint
    x: true
    y: true
    z: true
    roll: true
    pitch: true
    yaw: true
  - name: mounted_camera_optical_joint
    x: true
    y: true
    z: true
    roll: true
    pitch: true
    yaw: true
error_blocks:
 - name: camera1_to_arm
   type: chain3d_to_chain3d
   model_a: mounted_camera
   model_b: group1
 - name: camera2_to_arm
   type: chain3d_to_chain3d
   model_a: external_camera
   model_b: group1
 - name: restrict_camera
   type: outrageous
   param: external_camera_optical_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
 - name: restrict_camera
   type: outrageous
   param: mounted_camera_optical_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1