verbose: true
base_link: base_link
models:
 - name: group1
   type: chain
   frame: link_6
 - name: camera
   type: camera3d
   frame: world
   topic: /camera/depth_registered/points
free_params:
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
free_frames:
  - name: checkerboard
    x: true
    y: false
    z: true
    roll: false
    ptich: true
    yaw: false
  - name: camera
    x: true
    y: true
    z: true
    roll: true
    pitch: true
    yaw: true