chains:
  - name: group1
    topic: /group1_controller/follow_group1_trajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    planning_group: group1
duration: 2.0
features:
  checkerboard_finder:
    type: robot_calibration/CheckerboardFinder
    topic: /camera/depth_registered/points
    camera_sensor_name: camera
    chain_sensor_name: group1